### ISSUE TITLE
Printable Mode + Gc

### ISSUE THREAD

**Issue by Chocohead** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#30]
Looking at any page in printable mode (from the tools section on the left, eg: http://ftb.gamepedia.com/index.php?title=EV-Transformer&printable=yes), all the crafting grid icons are shifted up and to the left by a few pixels, any chance of a fix?

**Comment by ghost** [comment]
``` css
@media print {
    .CraftingGridCell {
        padding: 2px;
    }
}
```

Fix ^

Edit: May also want to fix margins for print mode and padding, stick this into the media print:

``` css
#pageWrapper {
    padding-left: 1em;
}
#content {
    padding: 10px !important;
}
```
